### ISSUE TITLE
Help me, i create a items for the unr3al_methlabs and get this error

### ISSUE THREAD

**Issue by ElNemo22** [1OSaft/unr3al_methlab#4]
![image](https://github.com/1OSaft/unr3al_methlab/assets/95186066/714e6c30-d7c5-4e4c-84e8-eeb884bfcf94)

**Comment by 1OSaft** [comment]
As the error states, the item "Metanfetamina" doesnt exist. Create it in ox_inventory, restart your server.
The item you use in the Config is the spawn name not label

**Comment by ElNemo22** [comment]
Thanks you @1OSaft
